notifications:
  email:
    - renato-jun.bellotti@student.ethz.ch

sudo: required

services:
  - docker

install:
  - docker-compose -f $TRAVIS_BUILD_DIR/docker-compose.yml -f $TRAVIS_BUILD_DIR/docker-compose.test.yml build
