version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${TQ_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tq_website
    ports:
      - "3309:3306"
    restart: always
  memcached:
    image: memcached:1.4
    restart: always
  django:
    build:
      context: .
      dockerfile: configurations/dockerfile
    user: root
    env_file:
      - .env
    volumes:
      - .:/webapps/tq_website
      - ./configurations/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    command: /bin/bash -c "python3 /webapps/tq_website/manage.py collectstatic --noinput && service rabbitmq-server start && supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    links:
      - db
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./configurations/nginx-ssl.conf:/etc/nginx/conf.d/tq_website.template
      - ./collected_static:/webapps/tq_website/collected_static
      - ./media:/webapps/tq_website/media
      - /etc/letsencrypt:/etc/letsencrypt
    command: nginx -g 'daemon off;' -c '/etc/nginx/conf.d/tq_website.template'
    environment:
      - NGINX_HOST=tq.ethz.ch
      - NGINX_PORT=80
    ports:
      - "80:80"
      - "443:443"
    links:
      - django
    restart: always
