version: '2'

# This Compose file can be used in a development environment.
#
# Useful commands:
#
# Run this: docker-compose -f docker-compose.yml down && docker-compose -f docker-compose.yml up -d --build
# Restore DB dump: docker exec -i tq_website_db_1 mysql -u root -p"ROOTPASSWORD" tq_website < dump.sql
# Connect to Postgres: docker exec -it tq-postgres psql -U root -d tq_website

services:

  # Database (Postgres)
  postgres:
    image: postgres:12
    container_name: tq-postgres
    environment:
      POSTGRES_USER: ${TQ_DB_USER}
      POSTGRES_PASSWORD: ${TQ_DB_PASSWORD}
      POSTGRES_DB: ${TQ_DB_NAME}
    volumes:
      - "postgres-volume:/var/lib/postgresql/data"
    ports:
      - "${TQ_DB_PORT_DEBUG_HOST}:5432"
    expose:
      - "5432"
    restart: always

  # Django (serving with debug webserver)
  django:
    container_name: tq-django
    build:
      context: .
      dockerfile: Dockerfile
    image: tq_website_django # give this built image a name to use it below
    env_file:
      - .env
    user: root
    volumes:
      - .:/app/:Z
    command: python3 -Wd manage.py runserver 0.0.0.0:8000
    ports:
      - "${TQ_DJANGO_PORT}:8000"
    links:
      - postgres
      - minio
    restart: always
    depends_on:
      - postgres
      - minio

  # S3 storage
  minio:
    container_name: tq-data
    image: minio/minio
    volumes:
      - s3-data-volume:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${TQ_S3_MEDIA_ACCESS_KEY}
      MINIO_SECRET_KEY: ${TQ_S3_MEDIA_SECRET_KEY}
    command: server /data

volumes:
  postgres-volume: # Let Docker generate a place for this, doesn't matter for development
  s3-data-volume:

