version: '2'
services:

  # Database (Postgres)
  postgres:
    image: postgres:12
    container_name: tq-postgres
    environment:
      POSTGRES_USER: ${TQ_DB_USER_POSTGRES}
      POSTGRES_PASSWORD: ${TQ_DB_PASSWORD_POSTGRES}
      POSTGRES_DB: tq_website
    volumes:
      - "../data-postgres:/var/lib/postgresql/data"
    ports:
      - "${TQ_DB_PORT_POSTGRES}:5432"
    restart: always

  # Cache and message broker for celery (handles background tasks)
  redis:
    container_name: tq-redis
    image: redis:3.2-alpine
    restart: always

  # Django (serving with gunicorn)
  django:
    container_name: tq-django
    build:
      context: .
      dockerfile: configurations/dockerfile
    image: tq_website_django # give this built image a name to use it below
    env_file:
      - .env
    user: root
    volumes:
      - .:/webapps/tq_website
    command: gunicorn -c /webapps/tq_website/configurations/gunicorn.py --chdir /webapps/tq_website tq_website.wsgi:application --reload
    links:
      - db
      - postgres
      - redis
    restart: always

  # Webserver
  nginx:
    container_name: tq-nginx
    image: nginx:mainline-alpine
    volumes:
      - ./configurations/nginx-ssl.conf:/etc/nginx/conf.d/tq_website.template
      - ./collected_static:/webapps/tq_website/collected_static
      - ./media:/webapps/tq_website/media
      - ./maintenance.conf:/webapps/tq_website/maintenance.conf
      - /etc/letsencrypt:/etc/letsencrypt
    command: nginx -g 'daemon off;' -c '/etc/nginx/conf.d/tq_website.template'
    environment:
      - NGINX_HOST=${TQ_NGINX_HOST}
      - NGINX_PORT=${TQ_NGINX_PORT}
    ports:
      - "${TQ_NGINX_PORT}:80"
      - "${TQ_SSL_PORT}:443"
    links:
      - django
    restart: always

  # Celery Beat
  beat:
    container_name: tq-beat
    image: tq_website_django
    env_file:
      - .env
    working_dir: /webapps/tq_website
    volumes:
      - .:/webapps/tq_website
    command: celery -A tq_website beat -l info --pidfile="/tmp/celerybeat.pid" -S django
    links:
      - db
      - postgres
      - redis
    depends_on:
      - django # ensure the image is built before running this container
    restart: always

  worker:
    container_name: tq-worker
    depends_on:
      - django # ensure the image is built before running this container
    image: tq_website_django
    env_file:
      - .env
    working_dir: /webapps/tq_website
    environment:
      C_FORCE_ROOT: 1
    volumes:
      - .:/webapps/tq_website
    command: celery -A tq_website worker -l info
    links:
      - db
      - postgres
      - redis
    restart: always
