version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${TQ_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tq_website
    ports:
      - "3309:3306"
  django:
    image: tq_website_django_new
    volumes:
      - .:/webapps
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - db

